---

- name: "Check for existing chocolatey install."
  win_stat:
    path: "{{ chocolatey_path }}/choco.exe"
  register: chocolatey_exe

- debug:
    var: chocolatey_exe
    verbosity: 2

- name: "Install Chocolatey."
  raw: "$env:chocolateyUseWindowsCompression='{{ chocolatey_windows_compression }}'; \
  iex ((New-Object System.Net.WebClient).DownloadString('{{ chocolatey_installer }}'))"
  when:
    - chocolatey_exe.stat.exists is defined
    - not chocolatey_exe.stat.exists

- name: "Add chocolatey to PATH."
  win_path:
    name: PATH
    elements: '%ALLUSERSPROFILE%\chocolatey\bin'
    scope: machine
    state: present
